[project]
name = "multitasking-tutorials"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiofiles>=24.1.0",
    "httpx>=0.28.1",
    "requests>=2.32.5",
    "scipy>=1.16.1",
    "typer>=0.16.0",
]
